///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BambooTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BambooTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("363d79d6-8526-4584-aad5-8ccf4c533ff2")]
    public partial class BambooTestRepository : RepoGenBaseFolder
    {
        static BambooTestRepository instance = new BambooTestRepository();
        BambooTestRepositoryFolders.GoogleAppFolder _google;

        /// <summary>
        /// Gets the singleton class instance representing the BambooTestRepository element repository.
        /// </summary>
        [RepositoryFolder("363d79d6-8526-4584-aad5-8ccf4c533ff2")]
        public static BambooTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BambooTestRepository() 
            : base("BambooTestRepository", "/", null, 0, false, "363d79d6-8526-4584-aad5-8ccf4c533ff2", ".\\RepositoryImages\\BambooTestRepository363d79d6.rximgres")
        {
            _google = new BambooTestRepositoryFolders.GoogleAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("363d79d6-8526-4584-aad5-8ccf4c533ff2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("4afaf88d-749c-4efc-aace-489ee91afca3")]
        public virtual BambooTestRepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class BambooTestRepositoryFolders
    {
        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("4afaf88d-749c-4efc-aace-489ee91afca3")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lstibInfo;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@domain='www.google.at']", parentFolder, 30000, null, false, "4afaf88d-749c-4efc-aace-489ee91afca3", "")
            {
                _lstibInfo = new RepoItemInfo(this, "LstIb", ".//input[#'lst-ib']", 30000, null, "10930299-dcaa-4d72-9b54-f279b3f28275");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4afaf88d-749c-4efc-aace-489ee91afca3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4afaf88d-749c-4efc-aace-489ee91afca3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LstIb item.
            /// </summary>
            [RepositoryItem("10930299-dcaa-4d72-9b54-f279b3f28275")]
            public virtual Ranorex.InputTag LstIb
            {
                get
                {
                    return _lstibInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LstIb item info.
            /// </summary>
            [RepositoryItemInfo("10930299-dcaa-4d72-9b54-f279b3f28275")]
            public virtual RepoItemInfo LstIbInfo
            {
                get
                {
                    return _lstibInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}